apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - base/namespace.yaml
  - base/configmap.yaml
  - middleware/mysql.yaml
  - middleware/redis.yaml
  - middleware/mongodb.yaml
  - middleware/minio.yaml
  - services/microservices.yaml
  - base/minio-ingress.yaml
  - base/minio-console-ingress.yaml
  - base/ingress.yaml
