apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zuoti-minio
  namespace: zuoti
spec:
  serviceName: zuoti-minio
  replicas: 1
  selector:
    matchLabels:
      app: zuoti-minio
  template:
    metadata:
      labels:
        app: zuoti-minio
    spec:
      containers:
        - name: minio
          image: minio/minio:RELEASE.2025-01-20T14-49-07Z
          args: ["server", "/data", "--console-address", ":9001"]
          ports:
            - containerPort: 9000
            - containerPort: 9001
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: zuoti-app-secret
                  key: MINIO_ACCESS_KEY
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: zuoti-app-secret
                  key: MINIO_SECRET_KEY
          volumeMounts:
            - name: data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 50Gi
---
apiVersion: v1
kind: Service
metadata:
  name: zuoti-minio
  namespace: zuoti
spec:
  selector:
    app: zuoti-minio
  ports:
    - name: api
      port: 9000
      targetPort: 9000
    - name: console
      port: 9001
      targetPort: 9001
