apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zuoti-mongodb
  namespace: zuoti
spec:
  serviceName: zuoti-mongodb
  replicas: 1
  selector:
    matchLabels:
      app: zuoti-mongodb
  template:
    metadata:
      labels:
        app: zuoti-mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:7
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: zuoti-app-secret
                  key: MONGODB_USER
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: zuoti-app-secret
                  key: MONGODB_PASSWORD
          volumeMounts:
            - name: data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  name: zuoti-mongodb
  namespace: zuoti
spec:
  selector:
    app: zuoti-mongodb
  ports:
    - port: 27017
      targetPort: 27017
